### ISSUE TITLE
imported and not used: "golang.org/x/mobile/app"

### ISSUE THREAD

**Issue by lostinblue** [jmank88/shinygames#1]
When using gomobile build I get the above error. Know any way around this issue?

**Comment by jmank88** [comment]
I did not write this with gomobile in mind, and have only tested it on a linux pc.

**Comment by lostinblue** [comment]
Oh I think I was confused because it includes some mobile libraries. 

I tried running it on linux but got:

    main.go:32: undefined: board

I'm mostly interested in seeing shiny examples so I can better understand it, it doesn't have to be specifically for mobile. Any assistance getting this to run is appreciated.

**Comment by jmank88** [comment]
Can you elaborate on the steps you are taking? I just checked out a fresh version of the repo on a new machine, and ran ```go build``` in the lightsout directory, with ```go1.6.1 linux/amd64```, to generate the ```lightsout``` executable, which runs fine.

**Comment by lostinblue** [comment]
I will give these steps a try soon as I have time to get back into research on engnines/uis for golang. Thank you for the additional instructions. I will close the ticket for now.

**Comment by lostinblue** [comment]
I did manage to solve the issue. Thanks for creating this example.
